#!/bin/bash
for arg in $@; do
    case $arg in
        "run")
            op_run=true
            ;;
        "clean")
            op_clean=true
            ;;
    esac
done

if [ "$op_clean" = true ]; then
    echo "Clearing..."
    rm -rf target
fi

# TODO: check if installed
echo "Building..."
RUST_TARGET_PATH=$PWD xargo build --target x86_64-pingos

if [ $? -eq 0 ]; then

    # TODO: check if installed
    echo "Creating image..."
    bootimage --target x86_64-pingos

    if [ "$op_run" = true ]; then
        # TODO: check if installed
        echo "Executing..."
        qemu-system-x86_64 -drive format=raw,file=bootimage.bin
    fi

fi
